name: Environment Variables
on:
 workflow_dispatch: 
env: 
 WORKFLOW_VAR: I_AM_WORKFLOW_SCROPED
jobs: 
 job1:
  runs-on: ubuntu-24.04 
  env:
   JOB_VAR: I_AM_JOB_1_SCROPED
  steps:
   - name: Inspect scopes job 1 step 1
     env:
      STEP_VAR:  I_AM_STEP_SCROPED 
     run: |
      echo "WORKFLOW_VAR $WORKFLOW_VAR"
      echo "JOB_VAR $JOB_VAR"
      echo "STEP_VAR $STEP_VAR"
   - name: Inspect scopes job 1 step 2
     run: | 
      echo "WORKFLOW_VAR: $WORKFLOW_VAR"
      echo "JOB_VAR: $JOB_VAR"
      echo "STEP_VAR: ${STEP_VAR:-<UNSET>}"
 job2:
  runs-on: ubuntu-24.04 
  steps:
   - name: Inspect scopes job 2 step 2
     run: |
      echo "WORKFLOW_VAR: $WORKFLOW_VAR"
      echo "JOB_VAR: $JOB_VAR"
      echo "STEP_VAR: ${STEP_VAR:-<UNSET>}"

      
